# Generated by Django 6.0 on 2025-12-17 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'returned_date'], name='book_loan_user_id_ba419f_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['book', 'returned_date'], name='book_loan_book_id_76a2ac_idx'),
        ),
    ]
